version: '3.5'
services:

    web-server:
        container_name: nginx
        image: nginx:latest
        ports:
            - 80:80
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - app

    app:
        container_name: flask
        build:
            context: ./flask
            dockerfile: Dockerfile
        env_file: mysql/database.conf
        expose: 
            - 8080
        depends_on:
            - database

    database:
        container_name: mysql
        image: mysql:latest
        env_file: mysql/database.conf
        volumes:
            - ./mysql/config.sql:/docker-entrypoint-initdb.d/config.sql
#         volumes:
#             - db_volume:/var/lib/mysql

# volumes:
#     db_volume: